name: esusu_weather_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  geolocator: ^13.0.2
  location_picker_flutter_map: ^3.1.0
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
