import 'package:flutter/material.dart';

enum WeatherCode {
  clearSky,
  mainlyClear,
  partlyCloudy,
  overcast,
  fog,
  depositingRimeFog,
  lightDrizzle,
  moderateDrizzle,
  denseDrizzle,
  lightFreezingDrizzle,
  denseFreezingDrizzle,
  slightRain,
  moderateRain,
  heavyRain,
  lightFreezingRain,
  heavyFreezingRain,
  slightSnowfall,
  moderateSnowfall,
  heavySnowfall,
  snowGrains,
  slightRainShowers,
  moderateRainShowers,
  violentRainShowers,
  slightSnowShowers,
  heavySnowShowers,
  slightThunderstorm,
  moderateThunderstorm,
  slightThunderstormWithHail,
  heavyThunderstormWithHail,
}

Map<int, WeatherCode> weatherCodeMap = {
  0: WeatherCode.clearSky,
  1: WeatherCode.mainlyClear,
  2: WeatherCode.partlyCloudy,
  3: WeatherCode.overcast,
  45: WeatherCode.fog,
  48: WeatherCode.depositingRimeFog,
  51: WeatherCode.lightDrizzle,
  53: WeatherCode.moderateDrizzle,
  55: WeatherCode.denseDrizzle,
  56: WeatherCode.lightFreezingDrizzle,
  57: WeatherCode.denseFreezingDrizzle,
  61: WeatherCode.slightRain,
  63: WeatherCode.moderateRain,
  65: WeatherCode.heavyRain,
  66: WeatherCode.lightFreezingRain,
  67: WeatherCode.heavyFreezingRain,
  71: WeatherCode.slightSnowfall,
  73: WeatherCode.moderateSnowfall,
  75: WeatherCode.heavySnowfall,
  77: WeatherCode.snowGrains,
  80: WeatherCode.slightRainShowers,
  81: WeatherCode.moderateRainShowers,
  82: WeatherCode.violentRainShowers,
  85: WeatherCode.slightSnowShowers,
  86: WeatherCode.heavySnowShowers,
  95: WeatherCode.slightThunderstorm,
  96: WeatherCode.slightThunderstormWithHail,
  99: WeatherCode.heavyThunderstormWithHail,
};

Map<WeatherCode, IconData> weatherIconMap = {
  WeatherCode.clearSky: Icons.wb_sunny,
  WeatherCode.mainlyClear: Icons.cloud,
  WeatherCode.partlyCloudy: Icons.cloud,
  WeatherCode.overcast: Icons.cloud,
  WeatherCode.fog: Icons.cloud,
  WeatherCode.depositingRimeFog: Icons.cloud,
  WeatherCode.lightDrizzle: Icons.umbrella,
  WeatherCode.moderateDrizzle: Icons.umbrella,
  WeatherCode.denseDrizzle: Icons.umbrella,
  WeatherCode.lightFreezingDrizzle: Icons.ac_unit,
  WeatherCode.denseFreezingDrizzle: Icons.ac_unit,
  WeatherCode.slightRain: Icons.grain,
  WeatherCode.moderateRain: Icons.umbrella,
  WeatherCode.heavyRain: Icons.umbrella,
  WeatherCode.lightFreezingRain: Icons.ac_unit,
  WeatherCode.heavyFreezingRain: Icons.ac_unit,
  WeatherCode.slightSnowfall: Icons.ac_unit,
  WeatherCode.moderateSnowfall: Icons.ac_unit,
  WeatherCode.heavySnowfall: Icons.ac_unit,
  WeatherCode.snowGrains: Icons.ac_unit,
  WeatherCode.slightRainShowers: Icons.umbrella,
  WeatherCode.moderateRainShowers: Icons.umbrella,
  WeatherCode.violentRainShowers: Icons.umbrella,
  WeatherCode.slightSnowShowers: Icons.ac_unit,
  WeatherCode.heavySnowShowers: Icons.ac_unit,
  WeatherCode.slightThunderstorm: Icons.thunderstorm,
  WeatherCode.moderateThunderstorm: Icons.thunderstorm,
  WeatherCode.slightThunderstormWithHail: Icons.thunderstorm,
  WeatherCode.heavyThunderstormWithHail: Icons.thunderstorm,
};

Map<WeatherCode, String> weatherDescriptionMap = {
  WeatherCode.clearSky: "Clear skies",
  WeatherCode.mainlyClear: "Mainly clear, with some clouds",
  WeatherCode.partlyCloudy: "Partly cloudy",
  WeatherCode.overcast: "Overcast",
  WeatherCode.fog: "Foggy",
  WeatherCode.depositingRimeFog: "Foggy with some frost forming",
  WeatherCode.lightDrizzle: "Lightly drizzling",
  WeatherCode.moderateDrizzle: "Moderately drizzling",
  WeatherCode.denseDrizzle: "Heavily drizzling",
  WeatherCode.lightFreezingDrizzle: "Lightly freezing drizzling",
  WeatherCode.denseFreezingDrizzle: "Heavily freezing drizzling",
  WeatherCode.slightRain: "Lightly raining",
  WeatherCode.moderateRain: "Moderately raining",
  WeatherCode.heavyRain: "Heavily raining",
  WeatherCode.lightFreezingRain: "Lightly freezing raining",
  WeatherCode.heavyFreezingRain: "Heavily freezing raining",
  WeatherCode.slightSnowfall: "Lightly snowing",
  WeatherCode.moderateSnowfall: "Moderately snowing",
  WeatherCode.heavySnowfall: "Heavily snowing",
  WeatherCode.snowGrains: "Lightly snowing with snow grains",
  WeatherCode.slightRainShowers: "Lightly raining with showers",
  WeatherCode.moderateRainShowers: "Moderately raining with showers",
  WeatherCode.violentRainShowers: "Heavily raining with showers",
  WeatherCode.slightSnowShowers: "Lightly snowing with showers",
  WeatherCode.heavySnowShowers: "Heavily snowing with showers",
  WeatherCode.slightThunderstorm: "Slightly thunderstorming",
  WeatherCode.moderateThunderstorm: "Moderately thunderstorming",
  WeatherCode.slightThunderstormWithHail: "Slightly thunderstorming with hail",
  WeatherCode.heavyThunderstormWithHail: "Heavily thunderstorming with hail",
};

extension WeatherCodeExtension on int {
  toWeatherCode() {
    return weatherCodeMap[this]!;
  }
}
